#!/usr/bin/env bash
# Regenerate the self-hosted browser bundle of the label-cache client used by
# demo/public/demo.html.
#
# The demo is the canonical consumer, so it consumes the service through the
# real client library (packages/label-cache-client) rather than a bespoke copy.
# Like the n3 bundle (scripts/ops/vendor-n3.sh), we self-host it as one same-origin
# ESM file instead of importing from a third-party CDN at runtime. The client is
# zero-dependency, so the bundle is just the library itself.
#
# Re-run this after changing the client (or bumping esbuild):
#   ./scripts/ops/vendor-label-client.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

ENTRY="packages/label-cache-client/src/index.ts"
OUT="demo/public/vendor/label-cache-client.mjs"

CLIENT_VERSION="$(node -p "require('./packages/label-cache-client/package.json').version")"
ESBUILD_VERSION="$(node -p "require('esbuild/package.json').version")"

mkdir -p "$(dirname "$OUT")"

pnpm exec esbuild "$ENTRY" \
  --bundle \
  --format=esm \
  --platform=browser \
  --target=es2022 \
  --minify \
  --legal-comments=none \
  --banner:js="// GENERATED by scripts/ops/vendor-label-client.sh — do not edit by hand.
// Self-hosted bundle of @rdf-label-cache/client@${CLIENT_VERSION} (zero deps),
// built with esbuild@${ESBUILD_VERSION} for demo/public/demo.html.
// Regenerate after changing the client: ./scripts/ops/vendor-label-client.sh" \
  --outfile="$OUT"

echo "Wrote $OUT — client@${CLIENT_VERSION}, $(wc -c < "$OUT" | tr -d ' ') bytes"
