#!/usr/bin/env bash
# Regenerate the self-hosted, single-file N3 browser bundle used by the demo page.
#
# demo/public/demo.html parses user-pasted Turtle with the `n3` library. Rather
# than importing it from a third-party CDN at runtime (which fanned out into ~18
# sequential cross-origin module requests), we bundle the pinned `n3` dependency
# into one same-origin ESM file served from our own edge. Zero third-party
# requests, version-pinned via package.json, reproducible from the lockfile.
#
# Re-run this after bumping `n3` (or `esbuild`) in package.json:
#   ./scripts/vendor-n3.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

ENTRY="scripts/vendor-n3.entry.mjs"
OUT="demo/public/vendor/n3.mjs"

N3_VERSION="$(node -p "require('n3/package.json').version")"
ESBUILD_VERSION="$(node -p "require('esbuild/package.json').version")"

mkdir -p "$(dirname "$OUT")"

pnpm exec esbuild "$ENTRY" \
  --bundle \
  --format=esm \
  --platform=browser \
  --target=es2022 \
  --minify \
  --legal-comments=none \
  --banner:js="// GENERATED by scripts/vendor-n3.sh — do not edit by hand.
// Self-hosted bundle of n3@${N3_VERSION} (+ its buffer/readable-stream deps),
// built with esbuild@${ESBUILD_VERSION} for demo/public/demo.html.
// Regenerate after bumping n3: ./scripts/vendor-n3.sh" \
  --outfile="$OUT"

echo "Wrote $OUT — n3@${N3_VERSION}, $(wc -c < "$OUT" | tr -d ' ') bytes"
